### ISSUE TITLE
Comments on Conclusion section

### ISSUE THREAD

**Issue by chrisn** [w3c/edge-computing-web-exploration#34]
The Conclusions section ends with

> The proposed next step is to draft the charter which is used to establish the proposed new working group.

I don't think this is ready for a Working Group yet, as we'll need to go through a design phase to figure out the details of proposed solutions. So my recommendation would be to form a CG to do that work. This could then lead to forming a WG, or taking proposed changes to existing WGs as appropriate.

**Comment by maxpassion** [comment]
> The Conclusions section ends with
> 
> > The proposed next step is to draft the charter which is used to establish the proposed new working group.
> 
> I don't think this is ready for a Working Group yet, as we'll need to go through a design phase to figure out the details of proposed solutions. So my recommendation would be to form a CG to do that work. This could then lead to forming a WG, or taking proposed changes to existing WGs as appropriate.

@chrisn How about deleting the last sentence?  Since this section focuses on the Conclusion and recommendations instead of the exact next step.

**Comment by chrisn** [comment]
I don't think simply removing the last sentence (i.e., "The proposed next step is to draft a charter to establish the proposed new working group.") is enough, as the preceding paragraph also describes creating a WG as the preferred approach.

So I suggest changing this section to say something like this:

> As analyzed in the gap analysis section and in the potential standards section, the proposed potential standards work is to specify a standardized common mechanism to offload code to the Edge Cloud. There may be multiple potential solutions and some of them may be related to WebAssembly and some may be related to web platform APIs.
>
> The proposed next step is to continue exploratory work on potential architecture and standardization proposals by forming a W3C Community Group, which would allow collaboration on solution designs. In future, this could lead to formation of a Working Group to standardize the group's chosen solutions.

**Comment by maxpassion** [comment]
> I don't think simply removing the last sentence (i.e., "The proposed next step is to draft a charter to establish the proposed new working group.") is enough, as the preceding paragraph also describes creating a WG as the preferred approach.
> 
> So I suggest changing this section to say something like this:
> 
> > As analyzed in the gap analysis section and in the potential standards section, the proposed potential standards work is to specify a standardized common mechanism to offload code to the Edge Cloud. There may be multiple potential solutions and some of them may be related to WebAssembly and some may be related to web platform APIs.
> > The proposed next step is to continue exploratory work on potential architecture and standardization proposals by forming a W3C Community Group, which would allow collaboration on solution designs. In future, this could lead to formation of a Working Group to standardize the group's chosen solutions.

@chrisnm, I am just thinking about whether forming a CG is the only way to move forward, but I am fine with this proposal. 
 Could you submit a PR? Then if nobody has objection we could merge it.

**Comment by chrisn** [comment]
I agree, I think we need to discuss the next steps but I can create a PR with that proposed text as a suggestion.

**Comment by maxpassion** [comment]
> I agree, I think we need to discuss the next steps but I can create a PR with that proposed text as a suggestion.

Hi Chris, we had a discussion in TPAC Web&Network IG meeting and there was a general consensus on forming a CG as the next step althoug there maybe challenges we need to solve. So I merged the PR at this time.

**Comment by dontcallmedom** [comment]
@chrisn can you confirm this issue can be closed? if so, I'll proceed with the transition request for the document

**Comment by chrisn** [comment]
I'm sorry I couldn't make the TPAC meeting, but the next step sounds good to me. Thank you @maxpassion and @dontcallmedom.
